version: "2"
services:
  stockquoteservice:
    build:
      context: ./stock-quote-service
    image: rprakashg/stockquoteservice
    container_name: stockquoteservice
    ports:
      - 8090:8090
    links:
      - graphite
    restart: always
    network_mode: bridge
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    network_mode: bridge
    ports:
      - 80:3000
    links:
      - graphite
      
  graphite:
    image: hopsoft/graphite-statsd
    container_name: graphite
    restart: always
    network_mode: bridge
    ports:
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126